version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-epos
    environment:
      POSTGRES_DB: TelescopeRentalPlatform
      POSTGRES_USER: eposuser
      POSTGRES_PASSWORD: epospass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
