server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TelescopeRentalPlatform
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jackson:
    serialization:
      indent_output: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${email_password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
        transport:
          protocol: smtp

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

springdoc:
  swagger-ui:
    enabled: true
